#line 1 "./Generated-Code/Lexer.m"

#line 3 "./Generated-Code/Lexer.m"

#define  YY_INT_ALIGNED short int

/* A lexical scanner generated by flex */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 6
#define YY_FLEX_SUBMINOR_VERSION 4
#if YY_FLEX_SUBMINOR_VERSION > 0
#define FLEX_BETA
#endif

#ifdef yyget_lval
#define yyget_lval_ALREADY_DEFINED
#else
#define yyget_lval yyget_lval
#endif

#ifdef yyset_lval
#define yyset_lval_ALREADY_DEFINED
#else
#define yyset_lval yyset_lval
#endif

/* First, we deal with  platform-specific or compiler-specific issues. */

/* begin standard C headers. */
#include <stdio.h>
#include <string.h>
#include <errno.h>
#include <stdlib.h>

/* end standard C headers. */

/* flex integer type definitions */

#ifndef FLEXINT_H
#define FLEXINT_H

/* C99 systems have <inttypes.h>. Non-C99 systems may or may not. */

#if defined (__STDC_VERSION__) && __STDC_VERSION__ >= 199901L

/* C99 says to define __STDC_LIMIT_MACROS before including stdint.h,
 * if you want the limit (max/min) macros for int types. 
 */
#ifndef __STDC_LIMIT_MACROS
#define __STDC_LIMIT_MACROS 1
#endif

#include <inttypes.h>
typedef int8_t flex_int8_t;
typedef uint8_t flex_uint8_t;
typedef int16_t flex_int16_t;
typedef uint16_t flex_uint16_t;
typedef int32_t flex_int32_t;
typedef uint32_t flex_uint32_t;
#else
typedef signed char flex_int8_t;
typedef short int flex_int16_t;
typedef int flex_int32_t;
typedef unsigned char flex_uint8_t; 
typedef unsigned short int flex_uint16_t;
typedef unsigned int flex_uint32_t;

/* Limits of integral types. */
#ifndef INT8_MIN
#define INT8_MIN               (-128)
#endif
#ifndef INT16_MIN
#define INT16_MIN              (-32767-1)
#endif
#ifndef INT32_MIN
#define INT32_MIN              (-2147483647-1)
#endif
#ifndef INT8_MAX
#define INT8_MAX               (127)
#endif
#ifndef INT16_MAX
#define INT16_MAX              (32767)
#endif
#ifndef INT32_MAX
#define INT32_MAX              (2147483647)
#endif
#ifndef UINT8_MAX
#define UINT8_MAX              (255U)
#endif
#ifndef UINT16_MAX
#define UINT16_MAX             (65535U)
#endif
#ifndef UINT32_MAX
#define UINT32_MAX             (4294967295U)
#endif

#ifndef SIZE_MAX
#define SIZE_MAX               (~(size_t)0)
#endif

#endif /* ! C99 */

#endif /* ! FLEXINT_H */

/* begin standard C++ headers. */

/* TODO: this is always defined, so inline it */
#define yyconst const

#if defined(__GNUC__) && __GNUC__ >= 3
#define yynoreturn __attribute__((__noreturn__))
#else
#define yynoreturn
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an
 *   integer in range [0..255] for use as an array index.
 */
#define YY_SC_TO_UI(c) ((YY_CHAR) (c))

/* An opaque pointer. */
#ifndef YY_TYPEDEF_YY_SCANNER_T
#define YY_TYPEDEF_YY_SCANNER_T
typedef void* yyscan_t;
#endif

/* For convenience, these vars (plus the bison vars far below)
   are macros in the reentrant scanner. */
#define yyin yyg->yyin_r
#define yyout yyg->yyout_r
#define yyextra yyg->yyextra_r
#define yyleng yyg->yyleng_r
#define yytext yyg->yytext_r
#define yylineno (YY_CURRENT_BUFFER_LVALUE->yy_bs_lineno)
#define yycolumn (YY_CURRENT_BUFFER_LVALUE->yy_bs_column)
#define yy_flex_debug yyg->yy_flex_debug_r

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN yyg->yy_start = 1 + 2 *
/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START ((yyg->yy_start - 1) / 2)
#define YYSTATE YY_START
/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)
/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart( yyin , yyscanner )
#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#ifndef YY_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k.
 * Moreover, YY_BUF_SIZE is 2*YY_READ_BUF_SIZE in the general case.
 * Ditto for the __ia64__ case accordingly.
 */
#define YY_BUF_SIZE 32768
#else
#define YY_BUF_SIZE 16384
#endif /* __ia64__ */
#endif

/* The state buf must be large enough to hold one state per character in the main buffer.
 */
#define YY_STATE_BUF_SIZE   ((YY_BUF_SIZE + 2) * sizeof(yy_state_type))

#ifndef YY_TYPEDEF_YY_BUFFER_STATE
#define YY_TYPEDEF_YY_BUFFER_STATE
typedef struct yy_buffer_state *YY_BUFFER_STATE;
#endif

#ifndef YY_TYPEDEF_YY_SIZE_T
#define YY_TYPEDEF_YY_SIZE_T
typedef size_t yy_size_t;
#endif

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2
    
    #define YY_LESS_LINENO(n)
    #define YY_LINENO_REWIND_TO(ptr)
    
/* Return all but the first "n" matched characters back to the input stream. */
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		*yy_cp = yyg->yy_hold_char; \
		YY_RESTORE_YY_MORE_OFFSET \
		yyg->yy_c_buf_p = yy_cp = yy_bp + yyless_macro_arg - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )
#define unput(c) yyunput( c, yyg->yytext_ptr , yyscanner )

#ifndef YY_STRUCT_YY_BUFFER_STATE
#define YY_STRUCT_YY_BUFFER_STATE
struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	int yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

    int yy_bs_lineno; /**< The line count. */
    int yy_bs_column; /**< The column count. */

	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;

#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2

	};
#endif /* !YY_STRUCT_YY_BUFFER_STATE */

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 *
 * Returns the top of the stack, or NULL.
 */
#define YY_CURRENT_BUFFER ( yyg->yy_buffer_stack \
                          ? yyg->yy_buffer_stack[yyg->yy_buffer_stack_top] \
                          : NULL)
/* Same as previous macro, but useful when we know that the buffer stack is not
 * NULL or when we need an lvalue. For internal use only.
 */
#define YY_CURRENT_BUFFER_LVALUE yyg->yy_buffer_stack[yyg->yy_buffer_stack_top]

void yyrestart ( FILE *input_file , yyscan_t yyscanner );
void yy_switch_to_buffer ( YY_BUFFER_STATE new_buffer , yyscan_t yyscanner );
YY_BUFFER_STATE yy_create_buffer ( FILE *file, int size , yyscan_t yyscanner );
void yy_delete_buffer ( YY_BUFFER_STATE b , yyscan_t yyscanner );
void yy_flush_buffer ( YY_BUFFER_STATE b , yyscan_t yyscanner );
void yypush_buffer_state ( YY_BUFFER_STATE new_buffer , yyscan_t yyscanner );
void yypop_buffer_state ( yyscan_t yyscanner );

static void yyensure_buffer_stack ( yyscan_t yyscanner );
static void yy_load_buffer_state ( yyscan_t yyscanner );
static void yy_init_buffer ( YY_BUFFER_STATE b, FILE *file , yyscan_t yyscanner );
#define YY_FLUSH_BUFFER yy_flush_buffer( YY_CURRENT_BUFFER , yyscanner)

YY_BUFFER_STATE yy_scan_buffer ( char *base, yy_size_t size , yyscan_t yyscanner );
YY_BUFFER_STATE yy_scan_string ( const char *yy_str , yyscan_t yyscanner );
YY_BUFFER_STATE yy_scan_bytes ( const char *bytes, int len , yyscan_t yyscanner );

void *yyalloc ( yy_size_t , yyscan_t yyscanner );
void *yyrealloc ( void *, yy_size_t , yyscan_t yyscanner );
void yyfree ( void * , yyscan_t yyscanner );

#define yy_new_buffer yy_create_buffer
#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){ \
        yyensure_buffer_stack (yyscanner); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer( yyin, YY_BUF_SIZE , yyscanner); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_is_interactive = is_interactive; \
	}
#define yy_set_bol(at_bol) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){\
        yyensure_buffer_stack (yyscanner); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer( yyin, YY_BUF_SIZE , yyscanner); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_at_bol = at_bol; \
	}
#define YY_AT_BOL() (YY_CURRENT_BUFFER_LVALUE->yy_at_bol)

/* Begin user sect3 */

#define yywrap(yyscanner) (/*CONSTCOND*/1)
#define YY_SKIP_YYWRAP
typedef flex_uint8_t YY_CHAR;

typedef int yy_state_type;

#define yytext_ptr yytext_r

static yy_state_type yy_get_previous_state ( yyscan_t yyscanner );
static yy_state_type yy_try_NUL_trans ( yy_state_type current_state  , yyscan_t yyscanner);
static int yy_get_next_buffer ( yyscan_t yyscanner );
static void yynoreturn yy_fatal_error ( const char* msg , yyscan_t yyscanner );

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	yyg->yytext_ptr = yy_bp; \
	yyleng = (int) (yy_cp - yy_bp); \
	yyg->yy_hold_char = *yy_cp; \
	*yy_cp = '\0'; \
	yyg->yy_c_buf_p = yy_cp;
#define YY_NUM_RULES 150
#define YY_END_OF_BUFFER 151
/* This struct is not used in this scanner,
   but its presence is necessary. */
struct yy_trans_info
	{
	flex_int32_t yy_verify;
	flex_int32_t yy_nxt;
	};
static const flex_int16_t yy_accept[222] =
    {   0,
        0,    0,  151,  150,  149,  144,  144,  144,  143,  143,
      143,  143,  143,  143,  143,  143,  143,  143,  143,  143,
      143,  143,  143,  143,  143,  149,  144,  144,  144,    0,
      145,  147,  146,  146,  143,  143,  143,  143,  143,  143,
      143,  143,  143,  143,  143,  143,  143,   51,  143,  143,
      143,  143,  143,  143,  143,  143,   58,   59,   57,  143,
      143,  143,  143,  143,  143,  143,  143,  143,  143,  143,
      143,  143,  143,  143,  143,   10,   16,  143,  143,   13,
      143,  143,   14,  143,   50,   64,   80,   72,   65,   81,
       73,   66,   82,   74,   67,   83,   75,   68,   84,   76,

       69,   85,   77,   63,   79,   71,   60,   62,   53,   61,
      143,   55,   54,   70,   86,   78,   25,   26,   27,   28,
       29,   30,   24,   31,  143,   12,    1,   15,   52,   17,
       21,   18,   22,   41,   42,   43,   44,   45,   46,   40,
       48,   47,   49,   11,    3,    4,    5,    6,    7,    8,
        9,    2,  120,  121,  122,  123,  124,  125,  119,  126,
      136,  137,  138,  139,  140,  141,  135,  142,  128,  129,
      130,  131,  132,  133,  127,  134,  112,  113,  114,  115,
      116,  117,  111,  118,   88,  104,   96,   89,  105,   97,
       90,  106,   98,   91,  107,   99,   92,  108,  100,   93,

      109,  101,   87,  103,   95,   56,   94,  110,  102,   33,
       34,   35,   36,   37,   38,   32,   39,   23,   19,   20,
        0
    } ;

static const YY_CHAR yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    3,    4,    5,
        6,    7,    8,    9,   10,   11,   11,    1,    1,    1,
        1,    1,    1,    1,   12,   13,   14,   15,   16,   17,
       18,   19,   20,   21,   22,   23,   24,   25,   26,   27,
       22,   28,   29,   30,   31,   32,   22,   33,   22,   34,
        1,    1,    1,    1,   35,    1,   36,   37,   36,   36,

       36,   36,   35,   38,   35,   35,   35,   35,   35,   35,
       39,   35,   35,   35,   40,   35,   35,   35,   35,   35,
       35,   35,    1,   41,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static const YY_CHAR yy_meta[42] =
    {   0,
        1,    1,    2,    2,    2,    2,    2,    2,    2,    2,
        2,    2,    2,    2,    2,    2,    2,    2,    2,    2,
        2,    2,    2,    2,    2,    2,    2,    2,    2,    2,
        2,    2,    2,    2,    2,    2,    2,    2,    2,    2,
        1
    } ;

static const flex_int16_t yy_base[224] =
    {   0,
        0,    0,  474,  553,   40,   78,   40,  117,  156,  458,
       30,   31,   33,  195,  233,   34,  270,   40,   38,   39,
       43,   45,    0,  301,   65,   69,    0,   98,    0,  340,
        0,  553,  553,  553,    0,  457,  455,  446,  438,    0,
        0,   75,   29,   64,   76,  114,   77,  124,  126,  116,
      182,  183,  186,  187,  220,  223,  437,   90,  129,  119,
      199,  125,   89,  226,  348,  195,  436,  196,  205,  229,
      269,  275,  378,  242,  116,  443,  434,  409,  429,  433,
      459,  489,  432,  519,  431,  334,    0,    0,  338,    0,
        0,  339,    0,    0,  342,    0,    0,  364,    0,    0,

      367,    0,    0,  370,  430,  429,  428,  427,  426,  425,
      235,  424,  423,  397,  422,  420,  417,  415,  414,  405,
      404,  403,  201,  238,  268,  404,  403,  402,  400,  257,
      387,  347,  386,    0,    0,    0,    0,    0,    0,  385,
      384,  383,  382,  380,    0,    0,    0,    0,    0,    0,
        0,  379,    0,    0,    0,    0,    0,    0,  385,  373,
        0,    0,    0,    0,    0,    0,  365,  356,    0,    0,
        0,    0,    0,    0,  355,  354,    0,    0,    0,    0,
        0,    0,  352,  351,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,

        0,    0,  339,  335,  279,  278,  277,  274,  262,    0,
        0,    0,    0,    0,    0,  243,  241,  239,  128,   73,
      553,   70,   48
    } ;

static const flex_int16_t yy_def[224] =
    {   0,
      221,    1,  221,  221,  221,  221,    6,  221,  221,    9,
        9,    9,    9,  222,  222,   15,   15,   15,   15,   15,
       15,   15,  223,  221,  223,  221,    6,    6,    8,    8,
       30,  221,  221,  221,   24,    9,    9,   15,   15,  223,
      223,   15,   15,    9,   15,   15,   15,   15,   15,  223,
      223,  223,  223,  223,  223,   15,   15,   15,   15,   15,
       15,   15,   15,   15,   15,   15,   15,   15,   15,   15,
       15,   15,   65,   15,  223,    9,   15,   15,    9,   15,
       65,   65,   15,   65,   15,  223,  223,  223,  223,  223,
      223,  223,  223,  223,  223,  223,  223,  223,  223,  223,

      223,  223,  223,   15,   15,   15,   15,   15,   15,   15,
       15,   15,   15,   15,   15,   15,  223,  223,  223,  223,
      223,  223,   15,   15,   15,   15,   15,   15,   15,   15,
       15,   15,   15,  223,  223,  223,  223,  223,  223,   15,
       15,   15,   15,   15,  223,  223,  223,  223,  223,  223,
      223,   15,   24,   24,   24,   24,   24,   24,    9,   15,
      223,  223,  223,  223,  223,  223,   15,   15,  223,  223,
      223,  223,  223,  223,   15,   15,  223,  223,  223,  223,
      223,  223,   15,   15,  223,  223,  223,  223,  223,  223,
      223,  223,  223,  223,  223,  223,  223,  223,  223,  223,

      223,  223,   15,   15,   15,   15,   15,   15,   15,  223,
      223,  223,  223,  223,  223,   15,   15,   15,   15,   15,
        0,  221,  221
    } ;

static const flex_int16_t yy_nxt[595] =
    {   0,
        4,    5,    6,    6,    7,    7,    7,    7,    7,    7,
        8,    9,   10,   11,   12,   13,   10,   14,   15,   16,
       17,   14,   18,   19,   20,   21,   14,   14,   22,   14,
       14,   14,   14,   14,   23,   24,   24,   23,   23,   25,
        4,   26,   28,   28,   36,   36,   44,   36,   42,   40,
       45,   38,   30,   43,   65,   78,   38,   46,   48,   49,
       38,   38,   38,   66,   68,   38,   26,   71,   67,   69,
       26,   38,   72,   70,   73,   74,   30,   79,   36,   26,
       27,   27,   28,   28,   28,   28,   28,   28,   29,   30,
       31,   30,   30,   30,   30,   38,   32,   38,   38,   38,

       28,   28,   77,   33,   75,  107,   83,   80,   26,  113,
       30,   38,   38,   30,   31,   32,   33,   26,   34,   29,
       29,   29,   29,   29,   29,   29,   29,   29,   30,   30,
       30,   30,   30,   30,   30,   32,   38,   84,   81,   85,
       86,   38,   87,   82,  108,  109,   38,   38,   38,   88,
       38,   38,   30,   30,   32,   75,  112,   32,   35,   35,
       35,   35,   35,   35,   35,   35,   35,   36,   36,   36,
       37,   36,   36,   38,   39,   38,   38,   38,   38,   38,
       38,   38,   38,   38,   38,   38,   38,   38,   38,   38,
       40,   35,   35,   41,   40,   40,   32,   40,   40,   40,

       40,   40,   40,   40,   40,   40,   89,   92,   90,   93,
       95,   98,   96,   99,  110,   91,   94,   38,   38,   97,
      100,   38,  127,   38,  111,  216,  125,   38,  128,   40,
       40,   40,   40,   40,   40,   40,   40,   40,   40,   40,
       40,   40,   40,   40,  101,   38,  102,  104,   38,  105,
      114,   38,  115,  103,  144,   47,  106,   38,  129,  116,
       38,   38,  217,   38,   38,   38,  206,   40,   40,   40,
       40,   40,   40,   50,   51,   52,   53,   54,   55,   38,
      130,   56,  131,  218,   38,   57,  132,   58,  133,  219,
       38,   38,   59,   60,   61,   62,   38,   38,   63,   38,

       38,   38,   64,   35,   35,   35,   35,   35,   35,   35,
       35,   35,   35,   35,   35,   35,   35,   35,   40,   41,
       40,   40,   40,   40,   40,   40,   40,   40,   40,   40,
       40,   40,   40,   40,   40,   40,   35,   35,   41,   40,
       40,   32,   30,   30,   30,   30,   30,   30,   30,   30,
       30,  117,  118,  119,  120,  121,  122,   38,  185,  123,
      186,   38,  188,  191,  189,  192,  194,  187,  195,   38,
       38,  190,  193,   38,   38,  196,   38,   38,   38,  220,
      124,  134,  135,  136,  137,  138,  139,   38,  197,  140,
      198,  200,   38,  201,  203,   38,  204,  199,  141,   36,

      202,   38,   38,  205,   38,   38,   38,   38,   38,   38,
      142,  143,  145,  146,  147,  148,  149,  150,  151,   38,
      152,  207,   38,  208,   38,   38,   38,  215,  214,  213,
      209,   38,  153,  154,  155,  156,  157,  158,  212,  211,
      159,  210,   38,   36,   38,   38,   38,   38,   38,   38,
       38,   38,   38,   38,   38,   38,   38,   36,  126,   38,
       38,  160,  161,  162,  163,  164,  165,  166,   38,   76,
      167,   36,   36,  221,  221,  221,  221,  221,  221,  221,
      221,  221,  221,  221,  221,  221,  221,  221,  221,  221,
      221,  168,  169,  170,  171,  172,  173,  174,  221,  221,

      175,  221,  221,  221,  221,  221,  221,  221,  221,  221,
      221,  221,  221,  221,  221,  221,  221,  221,  221,  221,
      221,  176,  177,  178,  179,  180,  181,  182,  221,  221,
      183,  221,  221,  221,  221,  221,  221,  221,  221,  221,
      221,  221,  221,  221,  221,  221,  221,  221,  221,  221,
      221,  184,    3,  221,  221,  221,  221,  221,  221,  221,
      221,  221,  221,  221,  221,  221,  221,  221,  221,  221,
      221,  221,  221,  221,  221,  221,  221,  221,  221,  221,
      221,  221,  221,  221,  221,  221,  221,  221,  221,  221,
      221,  221,  221,  221

    } ;

static const flex_int16_t yy_chk[595] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    5,    7,    7,   11,   12,   12,   13,   11,  223,
       12,   43,    7,   11,   18,   43,   16,   13,   16,   16,
       19,   20,   18,   19,   20,   21,   25,   22,   19,   20,
       26,  222,   22,   21,   22,   22,    7,   44,   44,    5,
        6,    6,    6,    6,    6,    6,    6,    6,    6,    6,
        6,    6,    6,    6,    6,  220,    6,   42,   45,   47,

       28,   28,   42,    6,   25,   58,   47,   45,   26,   63,
       28,   63,   58,    6,    6,    6,    6,   75,    6,    8,
        8,    8,    8,    8,    8,    8,    8,    8,    8,    8,
        8,    8,    8,    8,   28,    8,   46,   48,   46,   49,
       50,   60,   50,   46,   59,   60,   48,   62,   49,   50,
      219,   59,    8,    8,    8,   75,   62,    8,    9,    9,
        9,    9,    9,    9,    9,    9,    9,    9,    9,    9,
        9,    9,    9,    9,    9,    9,    9,    9,    9,    9,
        9,    9,    9,    9,    9,    9,    9,    9,    9,    9,
        9,    9,    9,    9,    9,    9,    9,   14,   14,   14,

       14,   14,   14,   14,   14,   14,   51,   52,   51,   52,
       53,   54,   53,   54,   61,   51,   52,   66,   68,   53,
       54,   61,   68,  123,   61,  123,   66,   69,   69,   14,
       14,   14,   14,   14,   14,   15,   15,   15,   15,   15,
       15,   15,   15,   15,   55,   56,   55,   56,   64,   56,
       64,   70,   64,   55,   74,   15,   56,  111,   70,   64,
      124,  218,  124,  217,   74,  216,  111,   15,   15,   15,
       15,   15,   15,   17,   17,   17,   17,   17,   17,  130,
       71,   17,   71,  125,  209,   17,   72,   17,   72,  130,
      125,   71,   17,   17,   17,   17,  208,   72,   17,  207,

      206,  205,   17,   24,   24,   24,   24,   24,   24,   24,
       24,   24,   24,   24,   24,   24,   24,   24,   24,   24,
       24,   24,   24,   24,   24,   24,   24,   24,   24,   24,
       24,   24,   24,   24,   24,   24,   24,   24,   24,   24,
       24,   24,   30,   30,   30,   30,   30,   30,   30,   30,
       30,   65,   65,   65,   65,   65,   65,  204,   86,   65,
       86,  203,   89,   92,   89,   92,   95,   86,   95,  132,
       65,   89,   92,  184,  183,   95,  176,  175,  168,  132,
       65,   73,   73,   73,   73,   73,   73,  167,   98,   73,
       98,  101,  104,  101,  104,  160,  104,   98,   73,  159,

      101,  152,  144,  104,  143,  142,  141,  140,  133,  131,
       73,   73,   78,   78,   78,   78,   78,   78,   78,  114,
       78,  114,  129,  114,  128,  127,  126,  122,  121,  120,
      114,   78,   79,   79,   79,   79,   79,   79,  119,  118,
       79,  117,  116,   79,  115,  113,  112,  110,  109,  108,
      107,  106,  105,   85,   83,   80,   77,   76,   67,   57,
       39,   79,   81,   81,   81,   81,   81,   81,   38,   37,
       81,   36,   10,    3,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,   81,   82,   82,   82,   82,   82,   82,    0,    0,

       82,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,   82,   84,   84,   84,   84,   84,   84,    0,    0,
       84,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,   84,  221,  221,  221,  221,  221,  221,  221,  221,
      221,  221,  221,  221,  221,  221,  221,  221,  221,  221,
      221,  221,  221,  221,  221,  221,  221,  221,  221,  221,
      221,  221,  221,  221,  221,  221,  221,  221,  221,  221,
      221,  221,  221,  221

    } ;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
#line 1 "./Source/Lexer.lm"
#line 2 "./Source/Lexer.lm"

#import "ParserConsumer.h"
#import "Parser.h"

#import "MixCommands.h"

#line 646 "./Generated-Code/Lexer.m"
#line 11 "./Source/Lexer.lm"
  // output files are set via command-line params in Makefile
  //%option header-file = "./Parser/Generated Code/lexer.h"
  //%option outfile     = "./Parser/Generated Code/lexer.m"
  //%option debug
  //%option nodefault
#define YY_NO_INPUT 1
#line 654 "./Generated-Code/Lexer.m"

#define INITIAL 0

#ifndef YY_NO_UNISTD_H
/* Special case for "unistd.h", since it is non-ANSI. We include it way
 * down here because we want the user's section 1 to have been scanned first.
 * The user has a chance to override it with an option.
 */
#include <unistd.h>
#endif

#ifndef YY_EXTRA_TYPE
#define YY_EXTRA_TYPE void *
#endif

/* Holds the entire state of the reentrant scanner. */
struct yyguts_t
    {

    /* User-defined. Not touched by flex. */
    YY_EXTRA_TYPE yyextra_r;

    /* The rest are the same as the globals declared in the non-reentrant scanner. */
    FILE *yyin_r, *yyout_r;
    size_t yy_buffer_stack_top; /**< index of top of stack. */
    size_t yy_buffer_stack_max; /**< capacity of stack. */
    YY_BUFFER_STATE * yy_buffer_stack; /**< Stack as an array. */
    char yy_hold_char;
    int yy_n_chars;
    int yyleng_r;
    char *yy_c_buf_p;
    int yy_init;
    int yy_start;
    int yy_did_buffer_switch_on_eof;
    int yy_start_stack_ptr;
    int yy_start_stack_depth;
    int *yy_start_stack;
    yy_state_type yy_last_accepting_state;
    char* yy_last_accepting_cpos;

    int yylineno_r;
    int yy_flex_debug_r;

    char *yytext_r;
    int yy_more_flag;
    int yy_more_len;

    YYSTYPE * yylval_r;

    }; /* end struct yyguts_t */

static int yy_init_globals ( yyscan_t yyscanner );

    /* This must go here because YYSTYPE and YYLTYPE are included
     * from bison output in section 1.*/
    #    define yylval yyg->yylval_r
    
int yylex_init (yyscan_t* scanner);

int yylex_init_extra ( YY_EXTRA_TYPE user_defined, yyscan_t* scanner);

/* Accessor methods to globals.
   These are made visible to non-reentrant scanners for convenience. */

int yylex_destroy ( yyscan_t yyscanner );

int yyget_debug ( yyscan_t yyscanner );

void yyset_debug ( int debug_flag , yyscan_t yyscanner );

YY_EXTRA_TYPE yyget_extra ( yyscan_t yyscanner );

void yyset_extra ( YY_EXTRA_TYPE user_defined , yyscan_t yyscanner );

FILE *yyget_in ( yyscan_t yyscanner );

void yyset_in  ( FILE * _in_str , yyscan_t yyscanner );

FILE *yyget_out ( yyscan_t yyscanner );

void yyset_out  ( FILE * _out_str , yyscan_t yyscanner );

			int yyget_leng ( yyscan_t yyscanner );

char *yyget_text ( yyscan_t yyscanner );

int yyget_lineno ( yyscan_t yyscanner );

void yyset_lineno ( int _line_number , yyscan_t yyscanner );

int yyget_column  ( yyscan_t yyscanner );

void yyset_column ( int _column_no , yyscan_t yyscanner );

YYSTYPE * yyget_lval ( yyscan_t yyscanner );

void yyset_lval ( YYSTYPE * yylval_param , yyscan_t yyscanner );

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap ( yyscan_t yyscanner );
#else
extern int yywrap ( yyscan_t yyscanner );
#endif
#endif

#ifndef YY_NO_UNPUT
    
#endif

#ifndef yytext_ptr
static void yy_flex_strncpy ( char *, const char *, int , yyscan_t yyscanner);
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen ( const char * , yyscan_t yyscanner);
#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
static int yyinput ( yyscan_t yyscanner );
#else
static int input ( yyscan_t yyscanner );
#endif

#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k */
#define YY_READ_BUF_SIZE 16384
#else
#define YY_READ_BUF_SIZE 8192
#endif /* __ia64__ */
#endif

/* Copy whatever the last rule matched to the standard output. */
#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO do { if (fwrite( yytext, (size_t) yyleng, 1, yyout )) {} } while (0)
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( YY_CURRENT_BUFFER_LVALUE->yy_is_interactive ) \
		{ \
		int c = '*'; \
		int n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else \
		{ \
		errno=0; \
		while ( (result = (int) fread(buf, 1, (yy_size_t) max_size, yyin)) == 0 && ferror(yyin)) \
			{ \
			if( errno != EINTR) \
				{ \
				YY_FATAL_ERROR( "input in flex scanner failed" ); \
				break; \
				} \
			errno=0; \
			clearerr(yyin); \
			} \
		}\
\

#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg , yyscanner)
#endif

/* end tables serialization structures and prototypes */

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL_IS_OURS 1

extern int yylex \
               (YYSTYPE * yylval_param , yyscan_t yyscanner);

#define YY_DECL int yylex \
               (YYSTYPE * yylval_param , yyscan_t yyscanner)
#endif /* !YY_DECL */

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK /*LINTED*/break;
#endif

#define YY_RULE_SETUP \
	YY_USER_ACTION

/** The main scanner function which does all the work.
 */
YY_DECL
{
	yy_state_type yy_current_state;
	char *yy_cp, *yy_bp;
	int yy_act;
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;

    yylval = yylval_param;

	if ( !yyg->yy_init )
		{
		yyg->yy_init = 1;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! yyg->yy_start )
			yyg->yy_start = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( ! YY_CURRENT_BUFFER ) {
			yyensure_buffer_stack (yyscanner);
			YY_CURRENT_BUFFER_LVALUE =
				yy_create_buffer( yyin, YY_BUF_SIZE , yyscanner);
		}

		yy_load_buffer_state( yyscanner );
		}

	{
#line 36 "./Source/Lexer.lm"



#line 930 "./Generated-Code/Lexer.m"

	while ( /*CONSTCOND*/1 )		/* loops until end-of-file is reached */
		{
		yy_cp = yyg->yy_c_buf_p;

		/* Support of yytext. */
		*yy_cp = yyg->yy_hold_char;

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = yyg->yy_start;
yy_match:
		do
			{
			YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)] ;
			if ( yy_accept[yy_current_state] )
				{
				yyg->yy_last_accepting_state = yy_current_state;
				yyg->yy_last_accepting_cpos = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 222 )
					yy_c = yy_meta[yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 553 );

yy_find_action:
		yy_act = yy_accept[yy_current_state];
		if ( yy_act == 0 )
			{ /* have to back up */
			yy_cp = yyg->yy_last_accepting_cpos;
			yy_current_state = yyg->yy_last_accepting_state;
			yy_act = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;

do_action:	/* This label is used only to access EOF actions. */

		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = yyg->yy_hold_char;
			yy_cp = yyg->yy_last_accepting_cpos;
			yy_current_state = yyg->yy_last_accepting_state;
			goto yy_find_action;

case 1:
YY_RULE_SETUP
#line 39 "./Source/Lexer.lm"
{  yylval->numericValue = CMD_NOP; return NOP; }
	YY_BREAK
case 2:
YY_RULE_SETUP
#line 40 "./Source/Lexer.lm"
{ yylval->numericValue = CMD_CMPA; return CMPA; }
	YY_BREAK
case 3:
YY_RULE_SETUP
#line 41 "./Source/Lexer.lm"
{ yylval->numericValue = CMD_CMP1; return CMP1; }
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 42 "./Source/Lexer.lm"
{ yylval->numericValue = CMD_CMP2; return CMP2; }
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 43 "./Source/Lexer.lm"
{ yylval->numericValue = CMD_CMP3; return CMP3; }
	YY_BREAK
case 6:
YY_RULE_SETUP
#line 44 "./Source/Lexer.lm"
{ yylval->numericValue = CMD_CMP4; return CMP4; }
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 45 "./Source/Lexer.lm"
{ yylval->numericValue = CMD_CMP5; return CMP5; }
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 46 "./Source/Lexer.lm"
{ yylval->numericValue = CMD_CMP6; return CMP6; }
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 47 "./Source/Lexer.lm"
{ yylval->numericValue = CMD_CMP7; return CMP7; }
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 48 "./Source/Lexer.lm"
{ yylval->numericValue = CMD_ADD; return ADD;  }
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 49 "./Source/Lexer.lm"
{ yylval->numericValue = CMD_SUB; return SUB; }
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 50 "./Source/Lexer.lm"
{ yylval->numericValue = CMD_MUL; return MUL; }
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 51 "./Source/Lexer.lm"
{ yylval->numericValue = CMD_DIB; return DIV;  }
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 52 "./Source/Lexer.lm"
{ yylval->numericValue = CMD_HLT; return HLT; }
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 53 "./Source/Lexer.lm"
{ yylval->numericValue = CMD_NUM; return NUM; }
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 54 "./Source/Lexer.lm"
{ yylval->numericValue = CMD_CHR; return CHR; }
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 55 "./Source/Lexer.lm"
{ yylval->numericValue = CMD_SLA; return SLA; }
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 56 "./Source/Lexer.lm"
{ yylval->numericValue = CMD_SRA; return SRA; }
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 57 "./Source/Lexer.lm"
{ yylval->numericValue = CMD_SLAX; return SLAX; }
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 58 "./Source/Lexer.lm"
{ yylval->numericValue = CMD_SRAX; return SRAX; }
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 59 "./Source/Lexer.lm"
{ yylval->numericValue = CMD_SLC; return SLC; }
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 60 "./Source/Lexer.lm"
{ yylval->numericValue = CMD_SRC; return SRC; }
	YY_BREAK
case 23:
YY_RULE_SETUP
#line 61 "./Source/Lexer.lm"
{ yylval->numericValue = CMD_MOVE; return MOVE; }
	YY_BREAK
case 24:
YY_RULE_SETUP
#line 62 "./Source/Lexer.lm"
{ yylval->numericValue = CMD_LDA; return LDA; }
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 63 "./Source/Lexer.lm"
{ yylval->numericValue = CMD_LD1; return LD1; }
	YY_BREAK
case 26:
YY_RULE_SETUP
#line 64 "./Source/Lexer.lm"
{ yylval->numericValue = CMD_LD2; return LD2; }
	YY_BREAK
case 27:
YY_RULE_SETUP
#line 65 "./Source/Lexer.lm"
{ yylval->numericValue = CMD_LD3; return LD3; }
	YY_BREAK
case 28:
YY_RULE_SETUP
#line 66 "./Source/Lexer.lm"
{ yylval->numericValue = CMD_LD4; return LD4; }
	YY_BREAK
case 29:
YY_RULE_SETUP
#line 67 "./Source/Lexer.lm"
{ yylval->numericValue = CMD_LD5; return LD5; }
	YY_BREAK
case 30:
YY_RULE_SETUP
#line 68 "./Source/Lexer.lm"
{ yylval->numericValue = CMD_LD6; return LD6; }
	YY_BREAK
case 31:
YY_RULE_SETUP
#line 69 "./Source/Lexer.lm"
{ yylval->numericValue = CMD_LDX; return LDX; }
	YY_BREAK
case 32:
YY_RULE_SETUP
#line 70 "./Source/Lexer.lm"
{ yylval->numericValue = CMD_LDAN; return LDAN; }
	YY_BREAK
case 33:
YY_RULE_SETUP
#line 71 "./Source/Lexer.lm"
{ yylval->numericValue = CMD_LD1N; return LD1N; }
	YY_BREAK
case 34:
YY_RULE_SETUP
#line 72 "./Source/Lexer.lm"
{ yylval->numericValue = CMD_LD2N; return LD2N; }
	YY_BREAK
case 35:
YY_RULE_SETUP
#line 73 "./Source/Lexer.lm"
{ yylval->numericValue = CMD_LD3N; return LD3N; }
	YY_BREAK
case 36:
YY_RULE_SETUP
#line 74 "./Source/Lexer.lm"
{ yylval->numericValue = CMD_LD4N; return LD4N; }
	YY_BREAK
case 37:
YY_RULE_SETUP
#line 75 "./Source/Lexer.lm"
{ yylval->numericValue = CMD_LD5N; return LD5N; }
	YY_BREAK
case 38:
YY_RULE_SETUP
#line 76 "./Source/Lexer.lm"
{ yylval->numericValue = CMD_LD6N; return LD6N; }
	YY_BREAK
case 39:
YY_RULE_SETUP
#line 77 "./Source/Lexer.lm"
{ yylval->numericValue = CMD_LD7N; return LDXN; }
	YY_BREAK
case 40:
YY_RULE_SETUP
#line 78 "./Source/Lexer.lm"
{ yylval->numericValue = CMD_STA; return STA; }
	YY_BREAK
case 41:
YY_RULE_SETUP
#line 79 "./Source/Lexer.lm"
{ yylval->numericValue = CMD_STA1; return ST1; }
	YY_BREAK
case 42:
YY_RULE_SETUP
#line 80 "./Source/Lexer.lm"
{ yylval->numericValue = CMD_STA2; return ST2; }
	YY_BREAK
case 43:
YY_RULE_SETUP
#line 81 "./Source/Lexer.lm"
{ yylval->numericValue = CMD_STA3; return ST3; }
	YY_BREAK
case 44:
YY_RULE_SETUP
#line 82 "./Source/Lexer.lm"
{ yylval->numericValue = CMD_STA4; return ST4; }
	YY_BREAK
case 45:
YY_RULE_SETUP
#line 83 "./Source/Lexer.lm"
{ yylval->numericValue = CMD_STA5; return ST5; }
	YY_BREAK
case 46:
YY_RULE_SETUP
#line 84 "./Source/Lexer.lm"
{ yylval->numericValue = CMD_STA6; return ST6; }
	YY_BREAK
case 47:
YY_RULE_SETUP
#line 85 "./Source/Lexer.lm"
{ yylval->numericValue = CMD_STX; return STX; }
	YY_BREAK
case 48:
YY_RULE_SETUP
#line 86 "./Source/Lexer.lm"
{ yylval->numericValue = CMD_STJ; return STJ; }
	YY_BREAK
case 49:
YY_RULE_SETUP
#line 87 "./Source/Lexer.lm"
{ yylval->numericValue = CMD_STZ; return STZ; }
	YY_BREAK
case 50:
YY_RULE_SETUP
#line 88 "./Source/Lexer.lm"
{ yylval->numericValue = CMD_IOC; return IOC; }
	YY_BREAK
case 51:
YY_RULE_SETUP
#line 89 "./Source/Lexer.lm"
{ yylval->numericValue = CMD_IN; return IN; }
	YY_BREAK
case 52:
YY_RULE_SETUP
#line 90 "./Source/Lexer.lm"
{ yylval->numericValue = CMD_OUT; return OUT; }
	YY_BREAK
case 53:
YY_RULE_SETUP
#line 91 "./Source/Lexer.lm"
{ yylval->numericValue = CMD_JMP; return JMP; }
	YY_BREAK
case 54:
YY_RULE_SETUP
#line 92 "./Source/Lexer.lm"
{ yylval->numericValue = CMD_JSJ; return JSJ; }
	YY_BREAK
case 55:
YY_RULE_SETUP
#line 93 "./Source/Lexer.lm"
{ yylval->numericValue = CMD_JOV; return JOV; }
	YY_BREAK
case 56:
YY_RULE_SETUP
#line 94 "./Source/Lexer.lm"
{ yylval->numericValue = CMD_JNOV; return JNOV; }
	YY_BREAK
case 57:
YY_RULE_SETUP
#line 95 "./Source/Lexer.lm"
{ yylval->numericValue = CMD_JL; return JL; }
	YY_BREAK
case 58:
YY_RULE_SETUP
#line 96 "./Source/Lexer.lm"
{ yylval->numericValue = CMD_JE; return JE; }
	YY_BREAK
case 59:
YY_RULE_SETUP
#line 97 "./Source/Lexer.lm"
{ yylval->numericValue = CMD_JG; return JG; }
	YY_BREAK
case 60:
YY_RULE_SETUP
#line 98 "./Source/Lexer.lm"
{ yylval->numericValue = CMD_JGE; return JGE; }
	YY_BREAK
case 61:
YY_RULE_SETUP
#line 99 "./Source/Lexer.lm"
{ yylval->numericValue = CMD_JNE; return JNE; }
	YY_BREAK
case 62:
YY_RULE_SETUP
#line 100 "./Source/Lexer.lm"
{ yylval->numericValue = CMD_JLE; return JLE; }
	YY_BREAK
case 63:
YY_RULE_SETUP
#line 101 "./Source/Lexer.lm"
{ yylval->numericValue = CMD_JAN; return JAN; }
	YY_BREAK
case 64:
YY_RULE_SETUP
#line 102 "./Source/Lexer.lm"
{ yylval->numericValue = CMD_J1N; return J1N; }
	YY_BREAK
case 65:
YY_RULE_SETUP
#line 103 "./Source/Lexer.lm"
{ yylval->numericValue = CMD_J2N; return J2N; }
	YY_BREAK
case 66:
YY_RULE_SETUP
#line 104 "./Source/Lexer.lm"
{ yylval->numericValue = CMD_J3N; return J3N; }
	YY_BREAK
case 67:
YY_RULE_SETUP
#line 105 "./Source/Lexer.lm"
{ yylval->numericValue = CMD_J4N; return J4N; }
	YY_BREAK
case 68:
YY_RULE_SETUP
#line 106 "./Source/Lexer.lm"
{ yylval->numericValue = CMD_J5N; return J5N; }
	YY_BREAK
case 69:
YY_RULE_SETUP
#line 107 "./Source/Lexer.lm"
{ yylval->numericValue = CMD_J6N; return J6N; }
	YY_BREAK
case 70:
YY_RULE_SETUP
#line 108 "./Source/Lexer.lm"
{ yylval->numericValue = CMD_J7N; return J7N; }
	YY_BREAK
case 71:
YY_RULE_SETUP
#line 109 "./Source/Lexer.lm"
{ yylval->numericValue = CMD_JAZ; return JAZ; }
	YY_BREAK
case 72:
YY_RULE_SETUP
#line 110 "./Source/Lexer.lm"
{ yylval->numericValue = CMD_J1Z; return J1Z; }
	YY_BREAK
case 73:
YY_RULE_SETUP
#line 111 "./Source/Lexer.lm"
{ yylval->numericValue = CMD_J2Z; return J2Z; }
	YY_BREAK
case 74:
YY_RULE_SETUP
#line 112 "./Source/Lexer.lm"
{ yylval->numericValue = CMD_J3Z; return J3Z; }
	YY_BREAK
case 75:
YY_RULE_SETUP
#line 113 "./Source/Lexer.lm"
{ yylval->numericValue = CMD_J4Z; return J4Z; }
	YY_BREAK
case 76:
YY_RULE_SETUP
#line 114 "./Source/Lexer.lm"
{ yylval->numericValue = CMD_J5Z; return J5Z; }
	YY_BREAK
case 77:
YY_RULE_SETUP
#line 115 "./Source/Lexer.lm"
{ yylval->numericValue = CMD_J6Z; return J6Z; }
	YY_BREAK
case 78:
YY_RULE_SETUP
#line 116 "./Source/Lexer.lm"
{ yylval->numericValue = CMD_JXZ; return JXZ; }
	YY_BREAK
case 79:
YY_RULE_SETUP
#line 117 "./Source/Lexer.lm"
{ yylval->numericValue = CMD_JAP; return JAP; }
	YY_BREAK
case 80:
YY_RULE_SETUP
#line 118 "./Source/Lexer.lm"
{ yylval->numericValue = CMD_J1P; return J1P; }
	YY_BREAK
case 81:
YY_RULE_SETUP
#line 119 "./Source/Lexer.lm"
{ yylval->numericValue = CMD_J2P; return J2P; }
	YY_BREAK
case 82:
YY_RULE_SETUP
#line 120 "./Source/Lexer.lm"
{ yylval->numericValue = CMD_J3P; return J3P; }
	YY_BREAK
case 83:
YY_RULE_SETUP
#line 121 "./Source/Lexer.lm"
{ yylval->numericValue = CMD_J4P; return J4P; }
	YY_BREAK
case 84:
YY_RULE_SETUP
#line 122 "./Source/Lexer.lm"
{ yylval->numericValue = CMD_J5P; return J5P; }
	YY_BREAK
case 85:
YY_RULE_SETUP
#line 123 "./Source/Lexer.lm"
{ yylval->numericValue = CMD_J6P; return J6P; }
	YY_BREAK
case 86:
YY_RULE_SETUP
#line 124 "./Source/Lexer.lm"
{ yylval->numericValue = CMD_JXP; return JXP; }
	YY_BREAK
case 87:
YY_RULE_SETUP
#line 125 "./Source/Lexer.lm"
{ yylval->numericValue = CMD_JANN; return JANN; }
	YY_BREAK
case 88:
YY_RULE_SETUP
#line 126 "./Source/Lexer.lm"
{ yylval->numericValue = CMD_J1NN; return J1NN; }
	YY_BREAK
case 89:
YY_RULE_SETUP
#line 127 "./Source/Lexer.lm"
{ yylval->numericValue = CMD_J2NN; return J2NN; }
	YY_BREAK
case 90:
YY_RULE_SETUP
#line 128 "./Source/Lexer.lm"
{ yylval->numericValue = CMD_J3NN; return J3NN; }
	YY_BREAK
case 91:
YY_RULE_SETUP
#line 129 "./Source/Lexer.lm"
{ yylval->numericValue = CMD_J4NN; return J4NN; }
	YY_BREAK
case 92:
YY_RULE_SETUP
#line 130 "./Source/Lexer.lm"
{ yylval->numericValue = CMD_J5NN; return J5NN; }
	YY_BREAK
case 93:
YY_RULE_SETUP
#line 131 "./Source/Lexer.lm"
{ yylval->numericValue = CMD_J6NN; return J6NN; }
	YY_BREAK
case 94:
YY_RULE_SETUP
#line 132 "./Source/Lexer.lm"
{ yylval->numericValue = CMD_JXNN; return JXNN; }
	YY_BREAK
case 95:
YY_RULE_SETUP
#line 133 "./Source/Lexer.lm"
{ yylval->numericValue = CMD_JANZ; return JANZ; }
	YY_BREAK
case 96:
YY_RULE_SETUP
#line 134 "./Source/Lexer.lm"
{ yylval->numericValue = CMD_J1NZ; return J1NZ; }
	YY_BREAK
case 97:
YY_RULE_SETUP
#line 135 "./Source/Lexer.lm"
{ yylval->numericValue = CMD_J2NZ; return J2NZ; }
	YY_BREAK
case 98:
YY_RULE_SETUP
#line 136 "./Source/Lexer.lm"
{ yylval->numericValue = CMD_J3NZ; return J3NZ; }
	YY_BREAK
case 99:
YY_RULE_SETUP
#line 137 "./Source/Lexer.lm"
{ yylval->numericValue = CMD_J4NZ; return J4NZ; }
	YY_BREAK
case 100:
YY_RULE_SETUP
#line 138 "./Source/Lexer.lm"
{ yylval->numericValue = CMD_J5NZ; return J5NZ; }
	YY_BREAK
case 101:
YY_RULE_SETUP
#line 139 "./Source/Lexer.lm"
{ yylval->numericValue = CMD_J6NZ; return J6NZ; }
	YY_BREAK
case 102:
YY_RULE_SETUP
#line 140 "./Source/Lexer.lm"
{ yylval->numericValue = CMD_JXNZ; return JXNZ; }
	YY_BREAK
case 103:
YY_RULE_SETUP
#line 141 "./Source/Lexer.lm"
{ yylval->numericValue = CMD_JANP; return JANP; }
	YY_BREAK
case 104:
YY_RULE_SETUP
#line 142 "./Source/Lexer.lm"
{ yylval->numericValue = CMD_J1NP; return J1NP; }
	YY_BREAK
case 105:
YY_RULE_SETUP
#line 143 "./Source/Lexer.lm"
{ yylval->numericValue = CMD_J2NP; return J2NP; }
	YY_BREAK
case 106:
YY_RULE_SETUP
#line 144 "./Source/Lexer.lm"
{ yylval->numericValue = CMD_J3NP; return J3NP; }
	YY_BREAK
case 107:
YY_RULE_SETUP
#line 145 "./Source/Lexer.lm"
{ yylval->numericValue = CMD_J4NP; return J4NP; }
	YY_BREAK
case 108:
YY_RULE_SETUP
#line 146 "./Source/Lexer.lm"
{ yylval->numericValue = CMD_J5NP; return J5NP; }
	YY_BREAK
case 109:
YY_RULE_SETUP
#line 147 "./Source/Lexer.lm"
{ yylval->numericValue = CMD_J6NP; return J6NP; }
	YY_BREAK
case 110:
YY_RULE_SETUP
#line 148 "./Source/Lexer.lm"
{ yylval->numericValue = CMD_JXNP; return JXNP; }
	YY_BREAK
case 111:
YY_RULE_SETUP
#line 149 "./Source/Lexer.lm"
{ yylval->numericValue = CMD_INCA; return INCA; }
	YY_BREAK
case 112:
YY_RULE_SETUP
#line 150 "./Source/Lexer.lm"
{ yylval->numericValue = CMD_INC1; return INC1; }
	YY_BREAK
case 113:
YY_RULE_SETUP
#line 151 "./Source/Lexer.lm"
{ yylval->numericValue = CMD_INC2; return INC2; }
	YY_BREAK
case 114:
YY_RULE_SETUP
#line 152 "./Source/Lexer.lm"
{ yylval->numericValue = CMD_INC3; return INC3; }
	YY_BREAK
case 115:
YY_RULE_SETUP
#line 153 "./Source/Lexer.lm"
{ yylval->numericValue = CMD_INC4; return INC4; }
	YY_BREAK
case 116:
YY_RULE_SETUP
#line 154 "./Source/Lexer.lm"
{ yylval->numericValue = CMD_INC5; return INC5; }
	YY_BREAK
case 117:
YY_RULE_SETUP
#line 155 "./Source/Lexer.lm"
{ yylval->numericValue = CMD_INC6; return INC6; }
	YY_BREAK
case 118:
YY_RULE_SETUP
#line 156 "./Source/Lexer.lm"
{ yylval->numericValue = CMD_INCX; return INCX; }
	YY_BREAK
case 119:
YY_RULE_SETUP
#line 157 "./Source/Lexer.lm"
{ yylval->numericValue = CMD_DECA; return DECA; }
	YY_BREAK
case 120:
YY_RULE_SETUP
#line 158 "./Source/Lexer.lm"
{ yylval->numericValue = CMD_DEC1; return DEC1; }
	YY_BREAK
case 121:
YY_RULE_SETUP
#line 159 "./Source/Lexer.lm"
{ yylval->numericValue = CMD_DEC2; return DEC2; }
	YY_BREAK
case 122:
YY_RULE_SETUP
#line 160 "./Source/Lexer.lm"
{ yylval->numericValue = CMD_DEC3; return DEC3; }
	YY_BREAK
case 123:
YY_RULE_SETUP
#line 161 "./Source/Lexer.lm"
{ yylval->numericValue = CMD_DEC4; return DEC4; }
	YY_BREAK
case 124:
YY_RULE_SETUP
#line 162 "./Source/Lexer.lm"
{ yylval->numericValue = CMD_DEC5; return DEC5; }
	YY_BREAK
case 125:
YY_RULE_SETUP
#line 163 "./Source/Lexer.lm"
{ yylval->numericValue = CMD_DEC6; return DEC6; }
	YY_BREAK
case 126:
YY_RULE_SETUP
#line 164 "./Source/Lexer.lm"
{ yylval->numericValue = CMD_DECX; return DECX; }
	YY_BREAK
case 127:
YY_RULE_SETUP
#line 165 "./Source/Lexer.lm"
{ yylval->numericValue = CMD_ENTA; return ENTA; }
	YY_BREAK
case 128:
YY_RULE_SETUP
#line 166 "./Source/Lexer.lm"
{ yylval->numericValue = CMD_ENT1; return ENT1; }
	YY_BREAK
case 129:
YY_RULE_SETUP
#line 167 "./Source/Lexer.lm"
{ yylval->numericValue = CMD_ENT2; return ENT2; }
	YY_BREAK
case 130:
YY_RULE_SETUP
#line 168 "./Source/Lexer.lm"
{ yylval->numericValue = CMD_ENT3; return ENT3; }
	YY_BREAK
case 131:
YY_RULE_SETUP
#line 169 "./Source/Lexer.lm"
{ yylval->numericValue = CMD_ENT4; return ENT4; }
	YY_BREAK
case 132:
YY_RULE_SETUP
#line 170 "./Source/Lexer.lm"
{ yylval->numericValue = CMD_ENT5; return ENT5; }
	YY_BREAK
case 133:
YY_RULE_SETUP
#line 171 "./Source/Lexer.lm"
{ yylval->numericValue = CMD_ENT6; return ENT6; }
	YY_BREAK
case 134:
YY_RULE_SETUP
#line 172 "./Source/Lexer.lm"
{ yylval->numericValue = CMD_ENTX; return ENTX; }
	YY_BREAK
case 135:
YY_RULE_SETUP
#line 173 "./Source/Lexer.lm"
{ yylval->numericValue = CMD_ENNA; return ENNA; }
	YY_BREAK
case 136:
YY_RULE_SETUP
#line 174 "./Source/Lexer.lm"
{ yylval->numericValue = CMD_ENN1; return ENN1; }
	YY_BREAK
case 137:
YY_RULE_SETUP
#line 175 "./Source/Lexer.lm"
{ yylval->numericValue = CMD_ENN2; return ENN2; }
	YY_BREAK
case 138:
YY_RULE_SETUP
#line 176 "./Source/Lexer.lm"
{ yylval->numericValue = CMD_ENN3; return ENN3; }
	YY_BREAK
case 139:
YY_RULE_SETUP
#line 177 "./Source/Lexer.lm"
{ yylval->numericValue = CMD_ENN4; return ENN4; }
	YY_BREAK
case 140:
YY_RULE_SETUP
#line 178 "./Source/Lexer.lm"
{ yylval->numericValue = CMD_ENN5; return ENN5; }
	YY_BREAK
case 141:
YY_RULE_SETUP
#line 179 "./Source/Lexer.lm"
{ yylval->numericValue = CMD_ENN6; return ENN6; }
	YY_BREAK
case 142:
YY_RULE_SETUP
#line 180 "./Source/Lexer.lm"
{ yylval->numericValue = CMD_ENNX; return ENNX; }
	YY_BREAK
case 143:
YY_RULE_SETUP
#line 182 "./Source/Lexer.lm"
{
        yylval->stringValue = strdup(yytext);
        retun Token_Label;
}
	YY_BREAK
case 144:
YY_RULE_SETUP
#line 188 "./Source/Lexer.lm"
{
    yylval->numericValue = (int)strtoul(yytext, NULL, 10);

    printf("[Lexer, number] %s\n", yytext);

    return Token_Number;
}
	YY_BREAK
case 145:
YY_RULE_SETUP
#line 196 "./Source/Lexer.lm"
{

    int result = 0;
    char *str = strdup(yytext);

    for (int i = 0; i < strlen(str)-1; i++) {
        result = result << 1;
        int bit = (str[i] == '1' ? 1 : 0);
        result += bit;
    }
    yylval->numericValue = result;

    printf("[Lexer, number] %s\n", yytext);

    return Token_Number;
}
	YY_BREAK
case 146:
YY_RULE_SETUP
#line 213 "./Source/Lexer.lm"
{
    int result = 0;
    char *str = strdup(yytext);

    for (int i = 0; i < strlen(str) -1; i++) {
        result *= 8;
        int bit = (str[i] - '0');
        result += bit;
    }
    yylval->numericValue = result;

    printf("[Lexer, number] %s\n", str);

    return Token_Number;
}
	YY_BREAK
case 147:
YY_RULE_SETUP
#line 229 "./Source/Lexer.lm"
{
    int result = 0;
    char *str = strdup(yytext);

    for (int i = 0; i < strlen(str)-1; i++) {
        result *= 16;
        int bit = 0;
        if (str[i] <= 9) {
            bit =  str[i] - '0';
        } else {
            bit = str[i] - 'A' + 10;
        }
        result += bit;
    }
    yylval->numericValue = result;

    printf("[Lexer, number] %s\n", str);

    return Token_Number;
}
	YY_BREAK
case 148:
YY_RULE_SETUP
#line 251 "./Source/Lexer.lm"
{
    yylval->stringValue = strdup(yytext);

    printf("[Lexer, string] %s\n", yytext);

    return Token_String;
}
	YY_BREAK
case 149:
YY_RULE_SETUP
#line 259 "./Source/Lexer.lm"
{}
	YY_BREAK
/**
   this is can act as default rule when %nodefault is enabled: just echo unknown input and do nothing
   
   . ECHO;
   \n ECHO;
  */
case YY_STATE_EOF(INITIAL):
#line 268 "./Source/Lexer.lm"
{
    printf("<<EOF>>\n");

    return 0;
}
	YY_BREAK
case 150:
YY_RULE_SETUP
#line 274 "./Source/Lexer.lm"
ECHO;
	YY_BREAK
#line 1814 "./Generated-Code/Lexer.m"

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - yyg->yytext_ptr) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = yyg->yy_hold_char;
		YY_RESTORE_YY_MORE_OFFSET

		if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between YY_CURRENT_BUFFER and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			yyg->yy_n_chars = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
			YY_CURRENT_BUFFER_LVALUE->yy_input_file = yyin;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( yyg->yy_c_buf_p <= &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[yyg->yy_n_chars] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			yyg->yy_c_buf_p = yyg->yytext_ptr + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state( yyscanner );

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state , yyscanner);

			yy_bp = yyg->yytext_ptr + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++yyg->yy_c_buf_p;
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = yyg->yy_c_buf_p;
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer( yyscanner ) )
			{
			case EOB_ACT_END_OF_FILE:
				{
				yyg->yy_did_buffer_switch_on_eof = 0;

				if ( yywrap( yyscanner ) )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					yyg->yy_c_buf_p = yyg->yytext_ptr + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! yyg->yy_did_buffer_switch_on_eof )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				yyg->yy_c_buf_p =
					yyg->yytext_ptr + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state( yyscanner );

				yy_cp = yyg->yy_c_buf_p;
				yy_bp = yyg->yytext_ptr + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				yyg->yy_c_buf_p =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[yyg->yy_n_chars];

				yy_current_state = yy_get_previous_state( yyscanner );

				yy_cp = yyg->yy_c_buf_p;
				yy_bp = yyg->yytext_ptr + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
	} /* end of user's declarations */
} /* end of yylex */

/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */
static int yy_get_next_buffer (yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
	char *dest = YY_CURRENT_BUFFER_LVALUE->yy_ch_buf;
	char *source = yyg->yytext_ptr;
	int number_to_move, i;
	int ret_val;

	if ( yyg->yy_c_buf_p > &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[yyg->yy_n_chars + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( YY_CURRENT_BUFFER_LVALUE->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( yyg->yy_c_buf_p - yyg->yytext_ptr - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) (yyg->yy_c_buf_p - yyg->yytext_ptr - 1);

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = yyg->yy_n_chars = 0;

	else
		{
			int num_to_read =
			YY_CURRENT_BUFFER_LVALUE->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = YY_CURRENT_BUFFER_LVALUE;

			int yy_c_buf_p_offset =
				(int) (yyg->yy_c_buf_p - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				int new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yyrealloc( (void *) b->yy_ch_buf,
							 (yy_size_t) (b->yy_buf_size + 2) , yyscanner );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = NULL;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			yyg->yy_c_buf_p = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = YY_CURRENT_BUFFER_LVALUE->yy_buf_size -
						number_to_move - 1;

			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move]),
			yyg->yy_n_chars, num_to_read );

		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = yyg->yy_n_chars;
		}

	if ( yyg->yy_n_chars == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart( yyin  , yyscanner);
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	if ((yyg->yy_n_chars + number_to_move) > YY_CURRENT_BUFFER_LVALUE->yy_buf_size) {
		/* Extend the array by 50%, plus the number we really need. */
		int new_size = yyg->yy_n_chars + number_to_move + (yyg->yy_n_chars >> 1);
		YY_CURRENT_BUFFER_LVALUE->yy_ch_buf = (char *) yyrealloc(
			(void *) YY_CURRENT_BUFFER_LVALUE->yy_ch_buf, (yy_size_t) new_size , yyscanner );
		if ( ! YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			YY_FATAL_ERROR( "out of dynamic memory in yy_get_next_buffer()" );
		/* "- 2" to take care of EOB's */
		YY_CURRENT_BUFFER_LVALUE->yy_buf_size = (int) (new_size - 2);
	}

	yyg->yy_n_chars += number_to_move;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[yyg->yy_n_chars] = YY_END_OF_BUFFER_CHAR;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[yyg->yy_n_chars + 1] = YY_END_OF_BUFFER_CHAR;

	yyg->yytext_ptr = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[0];

	return ret_val;
}

/* yy_get_previous_state - get the state just before the EOB char was reached */

    static yy_state_type yy_get_previous_state (yyscan_t yyscanner)
{
	yy_state_type yy_current_state;
	char *yy_cp;
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;

	yy_current_state = yyg->yy_start;

	for ( yy_cp = yyg->yytext_ptr + YY_MORE_ADJ; yy_cp < yyg->yy_c_buf_p; ++yy_cp )
		{
		YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			yyg->yy_last_accepting_state = yy_current_state;
			yyg->yy_last_accepting_cpos = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 222 )
				yy_c = yy_meta[yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
		}

	return yy_current_state;
}

/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */
    static yy_state_type yy_try_NUL_trans  (yy_state_type yy_current_state , yyscan_t yyscanner)
{
	int yy_is_jam;
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner; /* This var may be unused depending upon options. */
	char *yy_cp = yyg->yy_c_buf_p;

	YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		yyg->yy_last_accepting_state = yy_current_state;
		yyg->yy_last_accepting_cpos = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 222 )
			yy_c = yy_meta[yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
	yy_is_jam = (yy_current_state == 221);

	(void)yyg;
	return yy_is_jam ? 0 : yy_current_state;
}

#ifndef YY_NO_UNPUT

#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
    static int yyinput (yyscan_t yyscanner)
#else
    static int input  (yyscan_t yyscanner)
#endif

{
	int c;
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;

	*yyg->yy_c_buf_p = yyg->yy_hold_char;

	if ( *yyg->yy_c_buf_p == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( yyg->yy_c_buf_p < &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[yyg->yy_n_chars] )
			/* This was really a NUL. */
			*yyg->yy_c_buf_p = '\0';

		else
			{ /* need more input */
			int offset = (int) (yyg->yy_c_buf_p - yyg->yytext_ptr);
			++yyg->yy_c_buf_p;

			switch ( yy_get_next_buffer( yyscanner ) )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					yyrestart( yyin , yyscanner);

					/*FALLTHROUGH*/

				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap( yyscanner ) )
						return 0;

					if ( ! yyg->yy_did_buffer_switch_on_eof )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput(yyscanner);
#else
					return input(yyscanner);
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					yyg->yy_c_buf_p = yyg->yytext_ptr + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) yyg->yy_c_buf_p;	/* cast for 8-bit char's */
	*yyg->yy_c_buf_p = '\0';	/* preserve yytext */
	yyg->yy_hold_char = *++yyg->yy_c_buf_p;

	return c;
}
#endif	/* ifndef YY_NO_INPUT */

/** Immediately switch to a different input stream.
 * @param input_file A readable stream.
 * @param yyscanner The scanner object.
 * @note This function does not reset the start condition to @c INITIAL .
 */
    void yyrestart  (FILE * input_file , yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;

	if ( ! YY_CURRENT_BUFFER ){
        yyensure_buffer_stack (yyscanner);
		YY_CURRENT_BUFFER_LVALUE =
            yy_create_buffer( yyin, YY_BUF_SIZE , yyscanner);
	}

	yy_init_buffer( YY_CURRENT_BUFFER, input_file , yyscanner);
	yy_load_buffer_state( yyscanner );
}

/** Switch to a different input buffer.
 * @param new_buffer The new input buffer.
 * @param yyscanner The scanner object.
 */
    void yy_switch_to_buffer  (YY_BUFFER_STATE  new_buffer , yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;

	/* TODO. We should be able to replace this entire function body
	 * with
	 *		yypop_buffer_state();
	 *		yypush_buffer_state(new_buffer);
     */
	yyensure_buffer_stack (yyscanner);
	if ( YY_CURRENT_BUFFER == new_buffer )
		return;

	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*yyg->yy_c_buf_p = yyg->yy_hold_char;
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = yyg->yy_c_buf_p;
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = yyg->yy_n_chars;
		}

	YY_CURRENT_BUFFER_LVALUE = new_buffer;
	yy_load_buffer_state( yyscanner );

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	yyg->yy_did_buffer_switch_on_eof = 1;
}

static void yy_load_buffer_state  (yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
	yyg->yy_n_chars = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
	yyg->yytext_ptr = yyg->yy_c_buf_p = YY_CURRENT_BUFFER_LVALUE->yy_buf_pos;
	yyin = YY_CURRENT_BUFFER_LVALUE->yy_input_file;
	yyg->yy_hold_char = *yyg->yy_c_buf_p;
}

/** Allocate and initialize an input buffer state.
 * @param file A readable stream.
 * @param size The character buffer size in bytes. When in doubt, use @c YY_BUF_SIZE.
 * @param yyscanner The scanner object.
 * @return the allocated buffer state.
 */
    YY_BUFFER_STATE yy_create_buffer  (FILE * file, int  size , yyscan_t yyscanner)
{
	YY_BUFFER_STATE b;
    
	b = (YY_BUFFER_STATE) yyalloc( sizeof( struct yy_buffer_state ) , yyscanner );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yyalloc( (yy_size_t) (b->yy_buf_size + 2) , yyscanner );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer( b, file , yyscanner);

	return b;
}

/** Destroy the buffer.
 * @param b a buffer created with yy_create_buffer()
 * @param yyscanner The scanner object.
 */
    void yy_delete_buffer (YY_BUFFER_STATE  b , yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;

	if ( ! b )
		return;

	if ( b == YY_CURRENT_BUFFER ) /* Not sure if we should pop here. */
		YY_CURRENT_BUFFER_LVALUE = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yyfree( (void *) b->yy_ch_buf , yyscanner );

	yyfree( (void *) b , yyscanner );
}

/* Initializes or reinitializes a buffer.
 * This function is sometimes called more than once on the same buffer,
 * such as during a yyrestart() or at EOF.
 */
    static void yy_init_buffer  (YY_BUFFER_STATE  b, FILE * file , yyscan_t yyscanner)

{
	int oerrno = errno;
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;

	yy_flush_buffer( b , yyscanner);

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

    /* If b is the current buffer, then yy_init_buffer was _probably_
     * called from yyrestart() or through yy_get_next_buffer.
     * In that case, we don't want to reset the lineno or column.
     */
    if (b != YY_CURRENT_BUFFER){
        b->yy_bs_lineno = 1;
        b->yy_bs_column = 0;
    }

        b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
    
	errno = oerrno;
}

/** Discard all buffered characters. On the next scan, YY_INPUT will be called.
 * @param b the buffer state to be flushed, usually @c YY_CURRENT_BUFFER.
 * @param yyscanner The scanner object.
 */
    void yy_flush_buffer (YY_BUFFER_STATE  b , yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == YY_CURRENT_BUFFER )
		yy_load_buffer_state( yyscanner );
}

/** Pushes the new state onto the stack. The new state becomes
 *  the current state. This function will allocate the stack
 *  if necessary.
 *  @param new_buffer The new state.
 *  @param yyscanner The scanner object.
 */
void yypush_buffer_state (YY_BUFFER_STATE new_buffer , yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
	if (new_buffer == NULL)
		return;

	yyensure_buffer_stack(yyscanner);

	/* This block is copied from yy_switch_to_buffer. */
	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*yyg->yy_c_buf_p = yyg->yy_hold_char;
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = yyg->yy_c_buf_p;
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = yyg->yy_n_chars;
		}

	/* Only push if top exists. Otherwise, replace top. */
	if (YY_CURRENT_BUFFER)
		yyg->yy_buffer_stack_top++;
	YY_CURRENT_BUFFER_LVALUE = new_buffer;

	/* copied from yy_switch_to_buffer. */
	yy_load_buffer_state( yyscanner );
	yyg->yy_did_buffer_switch_on_eof = 1;
}

/** Removes and deletes the top of the stack, if present.
 *  The next element becomes the new top.
 *  @param yyscanner The scanner object.
 */
void yypop_buffer_state (yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
	if (!YY_CURRENT_BUFFER)
		return;

	yy_delete_buffer(YY_CURRENT_BUFFER , yyscanner);
	YY_CURRENT_BUFFER_LVALUE = NULL;
	if (yyg->yy_buffer_stack_top > 0)
		--yyg->yy_buffer_stack_top;

	if (YY_CURRENT_BUFFER) {
		yy_load_buffer_state( yyscanner );
		yyg->yy_did_buffer_switch_on_eof = 1;
	}
}

/* Allocates the stack if it does not exist.
 *  Guarantees space for at least one push.
 */
static void yyensure_buffer_stack (yyscan_t yyscanner)
{
	yy_size_t num_to_alloc;
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;

	if (!yyg->yy_buffer_stack) {

		/* First allocation is just for 2 elements, since we don't know if this
		 * scanner will even need a stack. We use 2 instead of 1 to avoid an
		 * immediate realloc on the next call.
         */
      num_to_alloc = 1; /* After all that talk, this was set to 1 anyways... */
		yyg->yy_buffer_stack = (struct yy_buffer_state**)yyalloc
								(num_to_alloc * sizeof(struct yy_buffer_state*)
								, yyscanner);
		if ( ! yyg->yy_buffer_stack )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		memset(yyg->yy_buffer_stack, 0, num_to_alloc * sizeof(struct yy_buffer_state*));

		yyg->yy_buffer_stack_max = num_to_alloc;
		yyg->yy_buffer_stack_top = 0;
		return;
	}

	if (yyg->yy_buffer_stack_top >= (yyg->yy_buffer_stack_max) - 1){

		/* Increase the buffer to prepare for a possible push. */
		yy_size_t grow_size = 8 /* arbitrary grow size */;

		num_to_alloc = yyg->yy_buffer_stack_max + grow_size;
		yyg->yy_buffer_stack = (struct yy_buffer_state**)yyrealloc
								(yyg->yy_buffer_stack,
								num_to_alloc * sizeof(struct yy_buffer_state*)
								, yyscanner);
		if ( ! yyg->yy_buffer_stack )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		/* zero only the new slots.*/
		memset(yyg->yy_buffer_stack + yyg->yy_buffer_stack_max, 0, grow_size * sizeof(struct yy_buffer_state*));
		yyg->yy_buffer_stack_max = num_to_alloc;
	}
}

/** Setup the input buffer state to scan directly from a user-specified character buffer.
 * @param base the character buffer
 * @param size the size in bytes of the character buffer
 * @param yyscanner The scanner object.
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_buffer  (char * base, yy_size_t  size , yyscan_t yyscanner)
{
	YY_BUFFER_STATE b;
    
	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return NULL;

	b = (YY_BUFFER_STATE) yyalloc( sizeof( struct yy_buffer_state ) , yyscanner );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

	b->yy_buf_size = (int) (size - 2);	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = NULL;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer( b , yyscanner );

	return b;
}

/** Setup the input buffer state to scan a string. The next call to yylex() will
 * scan from a @e copy of @a str.
 * @param yystr a NUL-terminated string to scan
 * @param yyscanner The scanner object.
 * @return the newly allocated buffer state object.
 * @note If you want to scan bytes that may contain NUL values, then use
 *       yy_scan_bytes() instead.
 */
YY_BUFFER_STATE yy_scan_string (const char * yystr , yyscan_t yyscanner)
{
    
	return yy_scan_bytes( yystr, (int) strlen(yystr) , yyscanner);
}

/** Setup the input buffer state to scan the given bytes. The next call to yylex() will
 * scan from a @e copy of @a bytes.
 * @param yybytes the byte buffer to scan
 * @param _yybytes_len the number of bytes in the buffer pointed to by @a bytes.
 * @param yyscanner The scanner object.
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_bytes  (const char * yybytes, int  _yybytes_len , yyscan_t yyscanner)
{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	int i;
    
	/* Get memory for full buffer, including space for trailing EOB's. */
	n = (yy_size_t) (_yybytes_len + 2);
	buf = (char *) yyalloc( n , yyscanner );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

	for ( i = 0; i < _yybytes_len; ++i )
		buf[i] = yybytes[i];

	buf[_yybytes_len] = buf[_yybytes_len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer( buf, n , yyscanner);
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
}

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

static void yynoreturn yy_fatal_error (const char* msg , yyscan_t yyscanner)
{
	struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
	(void)yyg;
	fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
}

/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		yytext[yyleng] = yyg->yy_hold_char; \
		yyg->yy_c_buf_p = yytext + yyless_macro_arg; \
		yyg->yy_hold_char = *yyg->yy_c_buf_p; \
		*yyg->yy_c_buf_p = '\0'; \
		yyleng = yyless_macro_arg; \
		} \
	while ( 0 )

/* Accessor  methods (get/set functions) to struct members. */

/** Get the user-defined data for this scanner.
 * @param yyscanner The scanner object.
 */
YY_EXTRA_TYPE yyget_extra  (yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
    return yyextra;
}

/** Get the current line number.
 * @param yyscanner The scanner object.
 */
int yyget_lineno  (yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;

        if (! YY_CURRENT_BUFFER)
            return 0;
    
    return yylineno;
}

/** Get the current column number.
 * @param yyscanner The scanner object.
 */
int yyget_column  (yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;

        if (! YY_CURRENT_BUFFER)
            return 0;
    
    return yycolumn;
}

/** Get the input stream.
 * @param yyscanner The scanner object.
 */
FILE *yyget_in  (yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
    return yyin;
}

/** Get the output stream.
 * @param yyscanner The scanner object.
 */
FILE *yyget_out  (yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
    return yyout;
}

/** Get the length of the current token.
 * @param yyscanner The scanner object.
 */
int yyget_leng  (yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
    return yyleng;
}

/** Get the current token.
 * @param yyscanner The scanner object.
 */

char *yyget_text  (yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
    return yytext;
}

/** Set the user-defined data. This data is never touched by the scanner.
 * @param user_defined The data to be associated with this scanner.
 * @param yyscanner The scanner object.
 */
void yyset_extra (YY_EXTRA_TYPE  user_defined , yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
    yyextra = user_defined ;
}

/** Set the current line number.
 * @param _line_number line number
 * @param yyscanner The scanner object.
 */
void yyset_lineno (int  _line_number , yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;

        /* lineno is only valid if an input buffer exists. */
        if (! YY_CURRENT_BUFFER )
           YY_FATAL_ERROR( "yyset_lineno called with no buffer" );
    
    yylineno = _line_number;
}

/** Set the current column.
 * @param _column_no column number
 * @param yyscanner The scanner object.
 */
void yyset_column (int  _column_no , yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;

        /* column is only valid if an input buffer exists. */
        if (! YY_CURRENT_BUFFER )
           YY_FATAL_ERROR( "yyset_column called with no buffer" );
    
    yycolumn = _column_no;
}

/** Set the input stream. This does not discard the current
 * input buffer.
 * @param _in_str A readable stream.
 * @param yyscanner The scanner object.
 * @see yy_switch_to_buffer
 */
void yyset_in (FILE *  _in_str , yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
    yyin = _in_str ;
}

void yyset_out (FILE *  _out_str , yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
    yyout = _out_str ;
}

int yyget_debug  (yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
    return yy_flex_debug;
}

void yyset_debug (int  _bdebug , yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
    yy_flex_debug = _bdebug ;
}

/* Accessor methods for yylval and yylloc */

YYSTYPE * yyget_lval  (yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
    return yylval;
}

void yyset_lval (YYSTYPE *  yylval_param , yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
    yylval = yylval_param;
}

/* User-visible API */

/* yylex_init is special because it creates the scanner itself, so it is
 * the ONLY reentrant function that doesn't take the scanner as the last argument.
 * That's why we explicitly handle the declaration, instead of using our macros.
 */
int yylex_init(yyscan_t* ptr_yy_globals)
{
    if (ptr_yy_globals == NULL){
        errno = EINVAL;
        return 1;
    }

    *ptr_yy_globals = (yyscan_t) yyalloc ( sizeof( struct yyguts_t ), NULL );

    if (*ptr_yy_globals == NULL){
        errno = ENOMEM;
        return 1;
    }

    /* By setting to 0xAA, we expose bugs in yy_init_globals. Leave at 0x00 for releases. */
    memset(*ptr_yy_globals,0x00,sizeof(struct yyguts_t));

    return yy_init_globals ( *ptr_yy_globals );
}

/* yylex_init_extra has the same functionality as yylex_init, but follows the
 * convention of taking the scanner as the last argument. Note however, that
 * this is a *pointer* to a scanner, as it will be allocated by this call (and
 * is the reason, too, why this function also must handle its own declaration).
 * The user defined value in the first argument will be available to yyalloc in
 * the yyextra field.
 */
int yylex_init_extra( YY_EXTRA_TYPE yy_user_defined, yyscan_t* ptr_yy_globals )
{
    struct yyguts_t dummy_yyguts;

    yyset_extra (yy_user_defined, &dummy_yyguts);

    if (ptr_yy_globals == NULL){
        errno = EINVAL;
        return 1;
    }

    *ptr_yy_globals = (yyscan_t) yyalloc ( sizeof( struct yyguts_t ), &dummy_yyguts );

    if (*ptr_yy_globals == NULL){
        errno = ENOMEM;
        return 1;
    }

    /* By setting to 0xAA, we expose bugs in
    yy_init_globals. Leave at 0x00 for releases. */
    memset(*ptr_yy_globals,0x00,sizeof(struct yyguts_t));

    yyset_extra (yy_user_defined, *ptr_yy_globals);

    return yy_init_globals ( *ptr_yy_globals );
}

static int yy_init_globals (yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
    /* Initialization is the same as for the non-reentrant scanner.
     * This function is called from yylex_destroy(), so don't allocate here.
     */

    yyg->yy_buffer_stack = NULL;
    yyg->yy_buffer_stack_top = 0;
    yyg->yy_buffer_stack_max = 0;
    yyg->yy_c_buf_p = NULL;
    yyg->yy_init = 0;
    yyg->yy_start = 0;

    yyg->yy_start_stack_ptr = 0;
    yyg->yy_start_stack_depth = 0;
    yyg->yy_start_stack =  NULL;

/* Defined in main.c */
#ifdef YY_STDINIT
    yyin = stdin;
    yyout = stdout;
#else
    yyin = NULL;
    yyout = NULL;
#endif

    /* For future reference: Set errno on error, since we are called by
     * yylex_init()
     */
    return 0;
}

/* yylex_destroy is for both reentrant and non-reentrant scanners. */
int yylex_destroy  (yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;

    /* Pop the buffer stack, destroying each element. */
	while(YY_CURRENT_BUFFER){
		yy_delete_buffer( YY_CURRENT_BUFFER , yyscanner );
		YY_CURRENT_BUFFER_LVALUE = NULL;
		yypop_buffer_state(yyscanner);
	}

	/* Destroy the stack itself. */
	yyfree(yyg->yy_buffer_stack , yyscanner);
	yyg->yy_buffer_stack = NULL;

    /* Destroy the start condition stack. */
        yyfree( yyg->yy_start_stack , yyscanner );
        yyg->yy_start_stack = NULL;

    /* Reset the globals. This is important in a non-reentrant scanner so the next time
     * yylex() is called, initialization will occur. */
    yy_init_globals( yyscanner);

    /* Destroy the main struct (reentrant only). */
    yyfree ( yyscanner , yyscanner );
    yyscanner = NULL;
    return 0;
}

/*
 * Internal utility routines.
 */

#ifndef yytext_ptr
static void yy_flex_strncpy (char* s1, const char * s2, int n , yyscan_t yyscanner)
{
	struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
	(void)yyg;

	int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
}
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (const char * s , yyscan_t yyscanner)
{
	int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
}
#endif

void *yyalloc (yy_size_t  size , yyscan_t yyscanner)
{
	struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
	(void)yyg;
	return malloc(size);
}

void *yyrealloc  (void * ptr, yy_size_t  size , yyscan_t yyscanner)
{
	struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
	(void)yyg;

	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return realloc(ptr, size);
}

void yyfree (void * ptr , yyscan_t yyscanner)
{
	struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
	(void)yyg;
	free( (char *) ptr );	/* see yyrealloc() for (char *) cast */
}

#define YYTABLES_NAME "yytables"

#line 274 "./Source/Lexer.lm"


void yyerror (void *scanner, id <ParserConsumer> consumer, const char *msg) {
    printf(stderr, "%s\n", msg);

    abort();
}

